# Generated by Django 5.1 on 2024-08-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="blog/files/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="thumb_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/images/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, upload_to="profile_images"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=100),
        ),
    ]
