# Generated by Django 5.1 on 2024-08-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_tag_options_alter_tag_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
    ]
